# Generated by Django 5.2.4 on 2025-12-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_type', models.CharField(choices=[('starch', 'Starch'), ('protein', 'Protein'), ('vegetable', 'Vegetable'), ('beverage', 'Beverage'), ('snack', 'Snack')], max_length=20)),
                ('calories_per_unit', models.PositiveIntegerField()),
                ('protein_per_unit', models.FloatField()),
                ('carbs_per_unit', models.FloatField()),
                ('fats_per_unit', models.FloatField()),
                ('measurement_unit', models.CharField(max_length=50)),
            ],
        ),
    ]
