# Generated by Django 5.2.4 on 2026-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_weightlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meallog',
            name='protein',
            field=models.FloatField(default=0),
        ),
    ]
